title: My Technical Blog
email: 702407101@qq.com
description: >- 
  A blog about technology, programming, and other interesting stuff.
baseurl: "" # 这里必须是空的双引号
url: "https://youshuibuzhao.github.io" # 你的网站根域名
twitter_username: youshuibuzhao
github_username: youshuibuzhao

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
